name: adme-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - flask=1.1
  - flask-cors=3.0
  - joblib=0.15
  - keras=2.3.1
  - numpy=1.18
  - pip=20.0
  - python=3.8
  - rdkit=2020.03
  - scikit-learn=0.22
  - pip:
    - keras-self-attention==0.41.0

