servers:
  - url: https://opendata.ncats.nih.gov/adme/
  - url: https://adme.ncats.nih.gov/models/
openapi: 3.0.3
info:
  description: API documentation for ADME@NCATS prediction portal
  title: ADME API v1.0.1
  version: 1.0.1
  contact:
    name: Vishal Siramshetty
    x-role: responsible developer
    email: siramshettyv2@nih.gov
    x-id: https://github.com/iwwwish
  termsOfService: https://opendata.ncats.nih.gov/adme/
tags:
  - name: NCATS-API
paths:
  /api/v1/predict:
    get:
      summary: Returns ADME predictions for a given molecule and endpoint (or model).
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
        default:
          description: Default response.
          content:
            application/json:
              schema:
                type: object
      parameters:
        - name: smiles
          in: query
          required: true
          schema:
            type: string
            example: c1ccccc1
        - name: model
          in: query
          required: true
          schema:
            type: string
            example: solubility
